/** @type {import('prettier').Config} */
module.exports = {
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  printWidth: 120,
  singleQuote: true,
  trailingComma: 'all',
  importOrder: [
    '^server-only$',
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '^(@prisma/(.*)$)|^(prisma$)',
    '^(radix-ui/(.*)$)',
    '<THIRD_PARTY_MODULES>',
    '^types$',
    '^@/env(.*)$',
    '^@/types/(.*)$',
    '^@/app/(.*)$',
    '^@/components/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/(config/(.*)$)|^@/(config$)',
    '^@/(constants/(.*)$)|^@/(constants$)',
    '^@/hooks/(.*)$',
    '^@/lib/(.*)$',
    '^@/styles/(.*)$',
    '^[./]',
  ],
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
};
