import { env } from '@/env.mjs';
import { Provider } from '@/components/provider';
import { nextFont } from '@/lib/next-font';
import '@/styles/globals.css';
import { classNames } from '@/lib/class-names';

export const metadata = {
  title: env.NEXT_PUBLIC_APP_NAME,
  description: 'Generated by create next app',
};

export default function RootLayout(props: ReactProps) {
  return (
    <html lang="ja" className={classNames('antialiased', nextFont.className)} suppressHydrationWarning>
      <body>
        <Provider>{props.children}</Provider>
      </body>
    </html>
  );
}
