import SessionProvider from '@/components/provider/session-provider';
import TrackProvider from '@/components/provider/track-provider';
import { appName } from '@/constants';
import { nextFont } from '@/lib/next-font';
import '@/styles/globals.css';

export const metadata = {
  title: appName,
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <html lang="ja" className={nextFont.className}>
        <body>
          <TrackProvider>{children}</TrackProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
