import Footer from '@/components/footer';
import Header from '@/components/header';
import Loader from '@/components/loader';
import Provider from '@/components/provider';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Provider>
      <Header />
      {children}
      <Footer />
    </Provider>
  );
}
